source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.6"

gem "rails", "~> 7.0.1"
gem "logger"

gem "bootsnap", require: false
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"
gem "pg"
gem "dotenv-rails"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "rspec-rails"
  gem "factory_bot_rails"
end

group :test do
  gem "shoulda-matchers"
  gem "faker"
end

group :development do
end
