source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.6"

gem "logger"
gem "rails", "~> 7.1.0"

gem "bootsnap", require: false
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "dotenv-rails"
gem "jbuilder"
gem "pg"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 6.0"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "bullet"
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails"
  gem "faker"
  gem "rspec-rails"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end

group :test do
  gem "shoulda-matchers"
  gem "simplecov", require: false
end

group :development do
  gem "brakeman", require: false
  gem "bundler-audit", require: false
end
