name: Code Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: books_api_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/books_api_test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.6
        bundler-cache: true
        working-directory: books_api

    - name: Install SimpleCov
      working-directory: books_api
      run: |
        echo "gem 'simplecov', require: false" >> Gemfile
        bundle install

    - name: Set up database
      working-directory: books_api
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate

    - name: Run tests with coverage
      working-directory: books_api
      run: |
        COVERAGE=true bundle exec rspec

    - name: Upload coverage to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: books_api/coverage/
