name: Branch Protection

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-pr-requirements:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check for test files
      run: |
        if ! git diff --name-only origin/main...HEAD | grep -E "spec/.*\.rb$"; then
          echo "Warning: No test files found in this PR"
        fi

    - name: Check commit messages
      run: |
        # Check that commit messages follow conventional commit format
        git log --oneline origin/main..HEAD | while read line; do
          if ! echo "$line" | grep -qE "^[a-f0-9]+ (feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+"; then
            echo "Warning: Commit message doesn't follow conventional format: $line"
          fi
        done

  all-checks:
    needs: [check-pr-requirements]
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Check if all required jobs passed
      run: |
        echo "All PR checks completed"
        # This job will be used as a required status check
